services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_DATABASE: practica5
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
